### ISSUE TITLE
Not able to receive incoming call with voip notification in iOS

### ISSUE THREAD

**Issue by sandeepmanala** [sendbird/examples-calls-ios#14]
Hi Team
In iPhone not able to receive incoming calls, voip notification not coming, I have used same code sample project I can make call but not receiving call, In user profile push token is added but not getting calls.

**Comment by mininny** [comment]
Hi, are you using the quickstart sample to test the VoIP Push Notifications? The default push certificate will only work for the app in production(Sendbird Calls App on the Appstore). If you build the app yourself, the bundle id of the project will be different, so you will have to create and register your own push certificate to the Sendbird Dashboard.

Can you please confirm whether you're using Xcode to build the project?
